### ISSUE TITLE
problems running on linux

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-elm-test#29]
From elm-discuss:

I'm running Ubuntu 14.04.  It installs OK I think,.  Then (for example)

john@john:~/Development/elm/elm-binary-base64/test$ elm-test check/B64Check.elm
Exception thrown when attempting to run Elm compiler "elm-make":
TypeError: Incorrect value for stdio stream: inherit

or:

john@john:~/Development/elm/elm-binary-base64/test$ elm-test init
elm-package.json already exists

/usr/local/lib/node_modules/elm-test/bin/elm-test:41
      childProcess.execSync(elm["elm-package"] + " " + command + elmOptions, {
                   ^
TypeError: Object #<Object> has no method 'execSync'
    at execElmPackageSync (/usr/local/lib/node_modules/elm-test/bin/elm-test:41:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:45:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

(not at all sure what I'm doing here)

**Comment by avh4** [comment]
currently investigating...

**Comment by avh4** [comment]
Resolved by upgrading nodejs.  (See #31)
